export const SET_FRAMES_STATE = 'SET_FRAMES_STATE';
export const REPLACE_FRAMES_STATE = 'REPLACE_FRAMES_STATE';

export const SET_LAYOUTS_STATE = 'SET_LAYOUTS_STATE';
export const REPLACE_LAYOUTS_STATE = 'REPLACE_LAYOUTS_STATE';

export const SET_ROUTES_STATE = 'SET_ROUTES_STATE';
export const REPLACE_ROUTES_STATE = 'REPLACE_ROUTES_STATE';

export const SET_ERROR = 'SET_ERROR';
