// standard-table
export const LIST_STANDARD_TABLE_INIT = 'LIST_STANDARD_TABLE_INIT';
export const LIST_STANDARD_TABLE_GET = 'LIST_STANDARD_TABLE_GET';
export const LIST_STANDARD_TABLE_RESET = 'LIST_STANDARD_TABLE_RESET';
export const LIST_STANDARD_ONE_GET = 'LIST_STANDARD_ONE_GET';
export const LIST_STANDARD_MODALCLOSE = 'LIST_STANDARD_MODALCLOSE';

// edit-table
export const LIST_EDIT_TABLE_INIT = 'LIST_EDIT_TABLE_INIT';
export const LIST_EDIT_TABLE_GET = 'LIST_EDIT_TABLE_GET';
export const LIST_EDIT_TABLE_ADD = 'LIST_EDIT_TABLE_ADD';
export const LIST_EDIT_TABLE_EDIT = 'LIST_EDIT_TABLE_EDIT';
export const LIST_EDIT_TABLE_DEL = 'LIST_EDIT_TABLE_DEL';

// standard-list
export const LIST_STANDARD_INIT = 'LIST_STANDARD_INIT';
export const LIST_STANDARD_GET = 'LIST_STANDARD_GET';
export const LIST_STANDARD_APPROVED = 'LIST_STANDARD_APPROVED';

// card-list
export const LIST_CARD_INIT = 'LIST_CARD_INIT';
export const LIST_CARD_GET = 'LIST_CARD_GET';
export const LIST_CARD_APPROVED = 'LIST_CARD_APPROVED';
